"""Initial migration with index on reviews.book_id

Revision ID: 1b8e1da3f769
Revises: 3a7304f2cf39
Create Date: 2025-07-03 00:51:45.391237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8e1da3f769'
down_revision: Union[str, Sequence[str], None] = '3a7304f2cf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
