"""Initial migration with index on reviews.book_id

Revision ID: 3a7304f2cf39
Revises: 
Create Date: 2025-07-03 00:34:59.703462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7304f2cf39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_text', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=True))
    op.create_index('ix_reviews_book_id', 'reviews', ['book_id'], unique=False)
    op.drop_column('reviews', 'reviewer')
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.TEXT(), nullable=True))
    op.add_column('reviews', sa.Column('reviewer', sa.VARCHAR(), nullable=True))
    op.drop_index('ix_reviews_book_id', table_name='reviews')
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'review_text')
    # ### end Alembic commands ###
